[package]
name = "spellbreak-server-mod"
version = "0.1.0"
edition = "2021"

[lib]
name = "spellbreak_server_mod"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
ctor = "0.1.25"
retour = "0.1.0"
windows = "0.44.0"
winapi = { version = "0.3.9", features = ["winuser","libloaderapi"] }